export const EVENT_INFO = {
  name: 'Open National Athletics Championship 2026',
  organizer: 'Yuvrani Athletics Samiti, Alwar',
  venue: 'Hamirpur, Himachal Pradesh',
  date: '26-27 June 2026',
  contact: '9414317686',
  reportingTime: '08:30 AM',
  entryFee: 1275,
  closingDateKey: 'sportify_closing_date',
  entriesKey: 'sportify_entries',
  adminPasswordKey: 'sportify_admin_password',
  defaultAdminPassword: 'admin2026',
  defaultClosingDate: '2026-06-24T23:59',
  minEvents: 2,
  maxEvents: 3,
  events: [
    '100m',
    '200m',
    '400m',
    '800m',
    '1500m',
    'Long Jump',
    'High Jump',
    'Shot Put',
    'Javelin',
  ],
  ageCategories: [
    'Under 16',
    'Under 18',
    'Under 20',
    'Senior',
  ],
  genders: ['Male', 'Female', 'Other'],
}
